gophermart
pervukhinpm/gophermart pull request #1
Opened 2024-11-13 20:09 UTC by pervukhinpm

2024-12-17 23:42 UTC, bulbetski requested changes
В целом написано хорошо, самое основное -- добавить механизм миграций

2024-12-17 23:42 UTC, bulbetski commented on cmd/gophermart/main.go
> +		*appConfig,
Нет смысла разыменовывать, сделай так, чтобы NewConfig возвращать значение, либо чтобы NewDatabaseRepository принимал указатель на конфиг. (я бы выбрал 2 способ)

2024-12-17 23:42 UTC, bulbetski commented on cmd/gophermart/main.go
> +		context.Background(),
Контекст можно сделать отдельной переменной, чтобы в дальнейшем была возможность передавать его в другие фукнции

2024-12-17 23:42 UTC, bulbetski commented on cmd/gophermart/main.go
> +		middleware.Log.Error("Failed to initialize repository: %v", err)
Понятно, что логирование также является частью твоей мидлвари, но в данном случае оно вызывается из main, а не из middleware, что не является правильным. 
К примеру, можно иницализировать логгер отдельно в main, прокинуть его в middleware (и куда еще там надо будет) и также использовать этот инстанс логгера в main.go

2024-12-17 23:42 UTC, bulbetski commented on cmd/gophermart/main.go
> +		middleware.Log.Error("Failed to initialize repository: %v", err)
Как вариант можешь рассмотреть использование логгера через глобальную переменную

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +}
Рассмотри использования механизма миграций вместо их создания в репозитории.
https://github.com/pressly/goose

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +func NewDatabaseRepository(ctx context.Context, config config.Config) (*DatabaseRepository, error) {
Надо соблюдать принцип SRP, метод New должен выступать в роли контруктора -- передали внутрь нужные зависимости и без сайд эффектов просто вернули DatabaseRepository

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +	}
Вот это стоит вынести в main, вместе с defer db.Close() и передать внутрь конструктора как аргумент

2024-12-17 23:42 UTC, bulbetski commented on internal/service/accrual.go
> +}
Классно было бы реализовать воркер пул как отдельный пакет, чтобы ему можно было передавать любую задачу в любом из твоих сервисов. Тогда и код GophermartService станет чище

2024-12-17 23:42 UTC, bulbetski commented on internal/jwt/jwt.go
> +	SecretKey = "secret_key"
Захардкодили, лучше взять из ENV переменной

2024-12-17 23:42 UTC, bulbetski commented on internal/jwt/jwt.go
> +	SecretKey = "secret_key"
константы публичные, хотя они должны использоваться только внутри пакета, надо сделать приватными

2024-12-17 23:42 UTC, bulbetski commented on internal/jwt/jwt.go
> +		RegisteredClaims: jwt.RegisteredClaims{
Использование RegisteredClaims избыточно, если вы используете только ExpiresAt.
```
type Claims struct {
    UserID string `json:"user_id"`
    Exp    int64  `json:"exp"`
}
```

2024-12-17 23:42 UTC, bulbetski commented on internal/jwt/jwt.go
> +func BuildJWTString(userID string) (string, error) {
Метод создает и подписывает JWT-токен, а не просто "строит строку". Использование слова Build может ввести в заблуждение, так как оно обычно ассоциируется со сборкой объекта или подготовкой данных, а не с генерацией и подписыванием токенов.

Можно переименовать на
GenerateJWT
CreateSignedJWT

2024-12-17 23:42 UTC, bulbetski commented on internal/jwt/jwt.go
> +			return nil, fmt.Errorf("unexpected signed method: %v", t.Header["alg"])
не уверен, нужна ли проверка, скорее всего ее обеспечивает ParseWithClaims.
Думаю, можно сократить до
```
token, err := jwt.ParseWithClaims(tokenString, claims, func(t *jwt.Token) (interface{}, error) {
    return []byte(SecretKey), nil
})
```

2024-12-17 23:42 UTC, bulbetski commented on internal/luhn/luhn.go
> +func Calculate(number string) (string, error) {
Метод не используется

2024-12-17 23:42 UTC, bulbetski commented on internal/luhn/luhn.go
> +	}
Можно заменить на if number == "" {} -- так более читаемо

2024-12-17 23:42 UTC, bulbetski commented on internal/middleware/auth.go
> +		if authHeader == "" || !strings.HasPrefix(authHeader, "Bearer ") {
префикс "Bearer " стоит вынести в константу

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +func (dr *DatabaseRepository) GetOrders(ctx context.Context, userID string) (*[]model.Order, error) {
стоит добавить в запрос limit и offset, потому что заказов может быть очень много. Также limit и offset стоит добавить в параметры запроса

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +func (dr *DatabaseRepository) GetOrders(ctx context.Context, userID string) (*[]model.Order, error) {
Не нужно возвращать указатель на массив, лучше вернуть массив указателей

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +		order.Accrual = float64(intAccrual) / 100
для операций с "деньгами" и в целом с ариметикой float'ов лучше использовать библиотеку decimal. Такие библиотеки есть в каждом языке

2024-12-17 23:42 UTC, bulbetski commented on internal/repository/databaseRepository.go
> +		tx.Rollback(ctx)
tx.Rollback стоит написать в defer после tx

Обеспечивается гарантированный Rollback в случае ошибок и корректная обработка успешного Commit

2024-12-17 23:42 UTC, bulbetski commented on internal/service/accrual.go
> +		g.processAccrual(order)
надо избавиться от рекурсий, заменить рекурсию на цикл с таймером и лимитами для повторных попыток

2024-12-17 23:42 UTC, bulbetski commented on internal/service/accrual.go
> +		}
В случае ошибки парсинга заголовка, retryAfter будет возвращен некорректно (останется предыдущим значением)

Надо сделать что-то в духе
```
if retryAfterStr != "" {
    parsedRetryAfter, err := strconv.Atoi(retryAfterStr)
    if err == nil {
        retryAfter = parsedRetryAfter
    }
}
return nil, NewErrTooManyRequests(retryAfter)
```

2024-12-17 23:42 UTC, bulbetski commented on internal/service/accrual.go
> +	resp.Body.Close()
defer

2024-12-17 23:42 UTC, bulbetski commented on internal/service/order.go
> +func (g *GophermartService) GetOrdersByUserID(ctx context.Context, userID string) (*[]model.OrderResponse, error) {
Надо избавиться от указателя на массив. Можно заменить на массив указателей

2024-12-17 23:42 UTC, bulbetski commented on internal/service/user.go
> +	userBalance.Current = float64(user.Balance / 100)
Можно сделать какой-нибудь метод для конвертации из копеек в рубли. Этот метод будет использовать библиотеку decimal

2025-01-07 19:24 UTC, pervukhinpm commented
Добавил миграции с goose, использование env файла, вынес secret в env файл, убрал рекурсию в accrual service

2025-01-11 12:04 UTC, bulbetski requested changes
Посмотри комменты, которые ты не исправил. Там как правило твоих лайков не стоит. Исправишь -- будет супер и поставлю апрув

2025-01-26 00:15 UTC, bulbetski approved these changes
Всё ок

2026-07-22 09:01 UTC, merged